package gestion.administrativa.hospital.la;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class FormRecuperacionContraseña extends javax.swing.JFrame {

    private String usuario;
    private String correo_admin = "";
    private String codigo = "";
    /**
     * Creates new form correoElectronico
     */
    public FormRecuperacionContraseña(String usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
    }

    public void EnviarEmail(String correo){
        Login log = new Login();
        LblEnvioCorrectamente.setText("<html>Se envió un correo al gmail correspondiente<br>fijarse en spam</html>");
        RecuperacionContraseña recuperar = new RecuperacionContraseña();
        codigo = recuperar.GenerarCodigo();
        correo_admin = correo;
        recuperar.Enviar_Codigo(correo, codigo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        BtnAceptar = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        LblClave = new javax.swing.JLabel();
        LblEnvioCorrectamente = new javax.swing.JLabel();
        TxtFCorreo = new javax.swing.JTextField();
        TxtFClave = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperacion Constraseña");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 210, 40));

        LblTitulo.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("<html>RECUPERACIÓN DE<br>       CONTRASEÑA</html");
        LblTitulo.setToolTipText("");
        getContentPane().add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 280, -1));

        LblCorreo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 20)); // NOI18N
        LblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        LblCorreo.setText("CORREO ELECTRÓNICO");
        getContentPane().add(LblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 220, -1));

        LblClave.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 20)); // NOI18N
        LblClave.setForeground(new java.awt.Color(0, 0, 0));
        LblClave.setText("CODIGO DE VERIFICACIÓN");
        getContentPane().add(LblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, 30));

        LblEnvioCorrectamente.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        LblEnvioCorrectamente.setForeground(new java.awt.Color(0, 204, 0));
        LblEnvioCorrectamente.setToolTipText("");
        getContentPane().add(LblEnvioCorrectamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 210, 100));

        TxtFCorreo.setBackground(new java.awt.Color(255, 255, 255));
        TxtFCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TxtFCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtFCorreoKeyReleased(evt);
            }
        });
        getContentPane().add(TxtFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 230, 30));

        TxtFClave.setBackground(new java.awt.Color(255, 255, 255));
        TxtFClave.setForeground(new java.awt.Color(0, 0, 0));
        TxtFClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TxtFClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 230, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/recuperacioncontraseña.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        pack();
    }//GEN-END:initComponents

    private void TxtFCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFCorreoKeyReleased
        if(TxtFCorreo.getText().endsWith("@gmail.com"))
            EnviarEmail(TxtFCorreo.getText());
    }//GEN-LAST:event_TxtFCorreoKeyReleased

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        if (LblCorreo.getText() == "NUEVA CONTRASEÑA" && LblClave.getText() == "ESCRIBIR DE NUEVO LA CONTRASEÑA"){
            if (TxtFCorreo.getText().equals(TxtFClave.getText())){
                RecuperacionContraseña cambio = new RecuperacionContraseña();
                cambio.cambiarContrasena(correo_admin ,TxtFClave.getText());
                JOptionPane.showMessageDialog(this, "Usted cambió la contraseña correctamente.");
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(this, "Por favor escriba correctamente los 2 campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (TxtFClave.getText().equals(codigo)){
            JOptionPane.showMessageDialog(this, "Código correcto.");
            LblEnvioCorrectamente.setText("");
            LblCorreo.setText("NUEVA CONTRASEÑA");
            LblClave.setText("ESCRIBIR DE NUEVO LA CONTRASEÑA");
            TxtFCorreo.setText("");
            TxtFClave.setText("");
            return;
        }
        else
            JOptionPane.showMessageDialog(this, "La clave no coincide.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRecuperacionContraseña("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel LblClave;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblEnvioCorrectamente;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtFClave;
    private javax.swing.JTextField TxtFCorreo;
    // End of variables declaration//GEN-END:variables
}
