package gestion.administrativa.hospital.la;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class FormRecuperacionContraseña extends javax.swing.JFrame {

    private String usuario;
    private String correo_admin = "";
    private String codigo = "";
    /**
     * Creates new form correoElectronico
     */
    public FormRecuperacionContraseña(String usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
    }

    public void EnviarEmail(String correo){
        Login log = new Login();
        LblEnvioCorrectamente.setText("<html>Se envió un correo al gmail correspondiente<br>fijarse en spam</html>");
        RecuperacionContraseña recuperar = new RecuperacionContraseña();
        codigo = recuperar.GenerarCodigo();
        correo_admin = correo;
        recuperar.Enviar_Codigo(correo, codigo);
        TxtFClave.setText(codigo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        BtnAceptar = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        LblCorreo = new javax.swing.JLabel();
        LblClave = new javax.swing.JLabel();
        LblEnvioCorrectamente = new javax.swing.JLabel();
        TxtFCorreo = new javax.swing.JTextField();
        TxtFClave = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperacion Constraseña");
        setResizable(false);

        BtnAceptar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Chewy", 0, 36)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setText("RECUPERAR CONTRASEÑA");

        LblCorreo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        LblCorreo.setForeground(new java.awt.Color(0, 0, 0));
        LblCorreo.setText("CORREO ELECTRÓNICO");

        LblClave.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        LblClave.setForeground(new java.awt.Color(0, 0, 0));
        LblClave.setText("CODIGO DE VERIFICACIÓN");

        LblEnvioCorrectamente.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        LblEnvioCorrectamente.setForeground(new java.awt.Color(0, 204, 0));
        LblEnvioCorrectamente.setToolTipText("");

        TxtFCorreo.setBackground(new java.awt.Color(255, 255, 255));
        TxtFCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TxtFCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtFCorreoKeyReleased(evt);
            }
        });

        TxtFClave.setBackground(new java.awt.Color(255, 255, 255));
        TxtFClave.setForeground(new java.awt.Color(0, 0, 0));
        TxtFClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtFClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFClaveActionPerformed(evt);
            }
        });

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/background.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(LblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(TxtFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(LblClave, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(LblEnvioCorrectamente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(TxtFClave, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(LblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(TxtFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LblClave))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(LblEnvioCorrectamente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(LblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(TxtFClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }//GEN-END:initComponents

    private void TxtFClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFClaveActionPerformed

    private void TxtFCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFCorreoKeyReleased
        if(TxtFCorreo.getText().endsWith("@gmail.com"))
            EnviarEmail(TxtFCorreo.getText());
    }//GEN-LAST:event_TxtFCorreoKeyReleased

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        /*if (codigo == TxtFClave.getText()){
            LblCorreo.setText("NUEVA CONTRASEÑA");
            LblClave.setText("ESCRIBIR DE NUEVO LA CONTRASEÑA");
            return;
        }*/
        if (LblCorreo.getText() == "NUEVA CONTRASEÑA" && LblClave.getText() == "ESCRIBIR DE NUEVO LA CONTRASEÑA"){
            if (LblCorreo.getText() == LblClave.getText()){
                RecuperacionContraseña cambio = new RecuperacionContraseña();
                cambio.cambiarContrasena(correo_admin ,codigo);
            }
        }
        LblCorreo.setText("NUEVA CONTRASEÑA");
        LblClave.setText("ESCRIBIR DE NUEVO LA CONTRASEÑA");
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRecuperacionContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRecuperacionContraseña("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel LblClave;
    private javax.swing.JLabel LblCorreo;
    private javax.swing.JLabel LblEnvioCorrectamente;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtFClave;
    private javax.swing.JTextField TxtFCorreo;
    // End of variables declaration//GEN-END:variables
}
