/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;

import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;

import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;

public class FormAuditor extends javax.swing.JFrame {

    /**
     * Creates new form FormAuditor
     */
    public FormAuditor() {
        initComponents();
        this.setLocationRelativeTo(null);
        BtnAgendar.setBorder(new CompoundBorder(
                new LineBorder(Color.BLUE,5,true),
                new EmptyBorder(10,20,10,20)
        ));
        FontIcon icon = FontIcon.of(FontAwesomeSolid.CALENDAR, 35);
        icon.setIconColor(java.awt.Color.WHITE);
        BtnAgendar.setIcon(icon);
        BtnAgendar.setHorizontalTextPosition(SwingConstants.RIGHT);
        BtnAgendar.setVerticalTextPosition(SwingConstants.CENTER);
        BtnAgendar.setHorizontalAlignment(SwingConstants.LEFT);
        BtnAgendar.setHorizontalTextPosition(SwingConstants.RIGHT);
        BtnAgendar.setIconTextGap(5);
        
        FontIcon iconoregresar = FontIcon.of(FontAwesomeSolid.CHEVRON_LEFT);
        iconoregresar.setIconColor(java.awt.Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnauditoriaver = new javax.swing.JButton();
        IconMenu = new javax.swing.JLabel();
        BackgroundMenu = new javax.swing.JLabel();
        wsp = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblNumero1 = new javax.swing.JLabel();
        LblContacto = new javax.swing.JLabel();
        LblNumero3 = new javax.swing.JLabel();
        LblPacientes = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblCitas = new javax.swing.JLabel();
        BtnAgendar = new javax.swing.JButton();
        LblLoayza1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnauditoriaver.setText("ver auditoria");
        btnauditoriaver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnauditoriaverActionPerformed(evt);
            }
        });
        content.add(btnauditoriaver, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N
        IconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.add(IconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 82));

        BackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/menu.jpeg"))); // NOI18N
        content.add(BackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 730, 350));

        wsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/wsp.png"))); // NOI18N
        content.add(wsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 30));

        LblLoayza.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(236, 31, 54));
        LblLoayza.setText("LOAYZA NACIONAL");
        content.add(LblLoayza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        LblNumero1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero1.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero1.setText("0000");
        content.add(LblNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 60, -1));

        LblContacto.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LblContacto.setForeground(new java.awt.Color(6, 5, 235));
        LblContacto.setText("CONTACTO");
        content.add(LblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, -1));

        LblNumero3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero3.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero3.setText("217");
        content.add(LblNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        LblPacientes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblPacientes.setForeground(new java.awt.Color(6, 5, 235));
        LblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPacientes.setText("Pacientes");
        LblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 40));

        LblHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");
        content.add(LblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblCitas.setForeground(new java.awt.Color(48, 73, 101));
        LblCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCitas.setText("Citas médicas activas");
        content.add(LblCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, 40));

        BtnAgendar.setBackground(new java.awt.Color(0, 74, 173));
        BtnAgendar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgendar.setText("<html>AGENDAR<br>CITAS</html>");
        BtnAgendar.setToolTipText("");
        BtnAgendar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 173), 0, true));
        BtnAgendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgendar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgendarActionPerformed(evt);
            }
        });
        content.add(BtnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 20, 170, 70));

        LblLoayza1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblLoayza1.setForeground(new java.awt.Color(236, 31, 54));
        LblLoayza1.setText("LOAYZA NACIONAL");
        content.add(LblLoayza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(746, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesMouseClicked
        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Qué deseas hacer?\na) Registrar nuevos pacientes\nb) Buscar y eliminar",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "a", "b" },  // Opciones personalizadas
            "Sí"
        );
        if (opcion == JOptionPane.YES_OPTION) {
            PanelRegistroPacientes pacientes_registro = new PanelRegistroPacientes(content);
            pacientes_registro.setSize(740, 530);
            pacientes_registro.setLocation(0,0);
            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(pacientes_registro, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Registro de pacientes");
        } else if (opcion == JOptionPane.NO_OPTION) {
            PanelPacientes pacientes = new PanelPacientes(content);
            pacientes.setSize(740, 530);
            pacientes.setLocation(0,0);
            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(pacientes, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Pacientes");
        }
    }//GEN-LAST:event_LblPacientesMouseClicked

    private void LblPacientesLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblPacientesLblMouseEncimaOpciones

    private void LblPacientesLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblPacientesLblMouseSalirOpciones

    private void BtnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgendarActionPerformed
        PanelRegistrodeCitas registros = new PanelRegistrodeCitas(content);
        registros.setSize(740, 530);
        registros.setLocation(0,0);

        content.setLayout(new BorderLayout());
        content.removeAll();
        content.add(registros, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        this.setTitle("Registros");
    }//GEN-LAST:event_BtnAgendarActionPerformed

    private void btnauditoriaverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnauditoriaverActionPerformed
        FormAuditoria auditoria = new FormAuditoria();
        auditoria.setVisible(true);
    }//GEN-LAST:event_btnauditoriaverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAuditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAuditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMenu;
    private javax.swing.JButton BtnAgendar;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel LblCitas;
    private javax.swing.JLabel LblContacto;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblLoayza1;
    private javax.swing.JLabel LblNumero1;
    private javax.swing.JLabel LblNumero3;
    private javax.swing.JLabel LblPacientes;
    private javax.swing.JButton btnauditoriaver;
    private javax.swing.JPanel content;
    private javax.swing.JLabel wsp;
    // End of variables declaration//GEN-END:variables
}
