/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;

import org.kordamp.ikonli.swing.FontIcon;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
public class FormSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form FormSupervisor
     */
    public FormSupervisor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        content = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        btnauditoriaver = new javax.swing.JButton();
        BackgroundMenu = new javax.swing.JLabel();
        wsp = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblNumero1 = new javax.swing.JLabel();
        LblContacto = new javax.swing.JLabel();
        LblNumero3 = new javax.swing.JLabel();
        LblPacientes = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblMedicos = new javax.swing.JLabel();
        LblHistorialesClinicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N
        IconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.add(IconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 82));

        btnauditoriaver.setBackground(new java.awt.Color(153, 153, 255));
        btnauditoriaver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnauditoriaver.setForeground(new java.awt.Color(0, 0, 0));
        btnauditoriaver.setText("VER AUDITORIA");
        btnauditoriaver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnauditoriaverActionPerformed(evt);
            }
        });
        content.add(btnauditoriaver, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 143, 140, 30));

        BackgroundMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/menu.jpeg"))); // NOI18N
        content.add(BackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 730, 350));

        wsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/wsp.png"))); // NOI18N
        content.add(wsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 30));

        LblLoayza.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(236, 31, 54));
        LblLoayza.setText("LOAYZA NACIONAL");
        content.add(LblLoayza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        LblNumero1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero1.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero1.setText("0000");
        content.add(LblNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 60, -1));

        LblContacto.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LblContacto.setForeground(new java.awt.Color(6, 5, 235));
        LblContacto.setText("CONTACTO");
        content.add(LblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 100, -1));

        LblNumero3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero3.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero3.setText("217");
        content.add(LblNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        LblPacientes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblPacientes.setForeground(new java.awt.Color(6, 5, 235));
        LblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPacientes.setText("Pacientes");
        LblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, 40));

        LblHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");
        content.add(LblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        LblMedicos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblMedicos.setForeground(new java.awt.Color(6, 5, 235));
        LblMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMedicos.setText("Médicos");
        LblMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMedicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMedicosLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMedicosLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, 120, 40));

        LblHistorialesClinicos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblHistorialesClinicos.setForeground(new java.awt.Color(6, 5, 235));
        LblHistorialesClinicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHistorialesClinicos.setText("Historiales clínicos");
        LblHistorialesClinicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblHistorialesClinicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblHistorialesClinicosLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblHistorialesClinicosLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblHistorialesClinicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }//GEN-END:initComponents

    private void LblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesMouseClicked
        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Qué deseas hacer?\na) Registrar nuevos pacientes\nb) Buscar y eliminar",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "a", "b" },  // Opciones personalizadas
            "Sí"
        );
        if (opcion == JOptionPane.YES_OPTION) {
            PanelRegistroPacientes pacientes_registro = new PanelRegistroPacientes(content);
            pacientes_registro.setSize(740, 530);
            pacientes_registro.setLocation(0,0);
            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(pacientes_registro, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Registro de pacientes");
        } else if (opcion == JOptionPane.NO_OPTION) {
            PanelPacientes pacientes = new PanelPacientes(content);
            pacientes.setSize(740, 530);
            pacientes.setLocation(0,0);
            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(pacientes, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Pacientes");
        }
    }//GEN-LAST:event_LblPacientesMouseClicked

    private void LblPacientesLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblPacientesLblMouseEncimaOpciones

    private void LblPacientesLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblPacientesLblMouseSalirOpciones

    private void LblMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosMouseClicked
        this.setTitle("Medicos");

        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Qué deseas hacer?\na) Registrar nuevos médicos\nb) Buscar y eliminar",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] { "a", "b" },  // Opciones personalizadas
            "Sí"
        );
        if (opcion == JOptionPane.YES_OPTION) {
            PanelRegistroMedicos medicos_registro = new PanelRegistroMedicos(content);
            medicos_registro.setSize(740, 530);
            medicos_registro.setLocation(0,0);
            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(medicos_registro, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Registro de Médicos");
        } else if (opcion == JOptionPane.NO_OPTION) {
            PanelMedicos medicos = new PanelMedicos(content);
            medicos.setSize(740, 530);
            medicos.setLocation(0,0);

            content.setLayout(new BorderLayout());
            content.removeAll();
            content.add(medicos, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
            this.setTitle("Medicos");
        }
    }//GEN-LAST:event_LblMedicosMouseClicked

    private void LblMedicosLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblMedicosLblMouseEncimaOpciones

    private void LblMedicosLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblMedicosLblMouseSalirOpciones

    private void LblHistorialesClinicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHistorialesClinicosMouseClicked
        PanelHistorialClinico historial = new PanelHistorialClinico(content);
        historial.setSize(740, 530);
        historial.setLocation(0,0);

        content.setLayout(new BorderLayout());
        content.removeAll();
        content.add(historial, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        this.setTitle("Historiales Clínicos");
    }//GEN-LAST:event_LblHistorialesClinicosMouseClicked

    private void LblHistorialesClinicosLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHistorialesClinicosLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblHistorialesClinicosLblMouseEncimaOpciones

    private void LblHistorialesClinicosLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHistorialesClinicosLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblHistorialesClinicosLblMouseSalirOpciones

    private void btnauditoriaverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnauditoriaverActionPerformed
        FormAuditoria auditoria = new FormAuditoria();
        auditoria.setVisible(true);
    }//GEN-LAST:event_btnauditoriaverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMenu;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel LblContacto;
    private javax.swing.JLabel LblHistorialesClinicos;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblMedicos;
    private javax.swing.JLabel LblNumero1;
    private javax.swing.JLabel LblNumero3;
    private javax.swing.JLabel LblPacientes;
    private javax.swing.JButton btnauditoriaver;
    private javax.swing.JPanel content;
    private javax.swing.JLabel wsp;
    // End of variables declaration//GEN-END:variables
}
