/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;

import javax.swing.*;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.JLabel;



public class LoginForm extends javax.swing.JFrame {
    
    Login login = new Login();
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        logo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        chterminos = new javax.swing.JCheckBox();
        chdatos = new javax.swing.JCheckBox();
        lblterminos = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblOlvideContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N

        lblusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 0));
        lblusuario.setText("USUARIO");

        lblcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        lblcontraseña.setText("CONTRASEÑA");

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setForeground(new java.awt.Color(0, 0, 0));
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        txtcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbltitulo.setText("ACCEDE AL SISTEMA");

        chterminos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chterminos.setForeground(new java.awt.Color(255, 255, 255));
        chterminos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        chdatos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chdatos.setForeground(new java.awt.Color(0, 0, 0));
        chdatos.setText("<html>HE LEÍDO Y ACEPTO EL TRATAMIENTO DE MIS DATOS PERSONALES<br>PARA FINALIDADES ADICONALES<html>");
        chdatos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblterminos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblterminos.setForeground(new java.awt.Color(0, 0, 0));
        lblterminos.setText("<html><u>TERMINOS Y CONDICIONES</u></html>");
        lblterminos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelMouseEncima(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelMouseSalir(evt);
            }
        });

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/banner.jpeg"))); // NOI18N

        LblLoayza.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(255, 39, 40));
        LblLoayza.setText("LOAYZA NACIONAL");

        LblHospital.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");

        LblOlvideContraseña.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LblOlvideContraseña.setForeground(new java.awt.Color(0, 0, 0));
        LblOlvideContraseña.setText("<html><u>OLVIDE MI<br>CONTRASEÑA</u></html>");
        LblOlvideContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblOlvideContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelMouseEncima(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelMouseSalir(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblHospital)
                            .addComponent(LblLoayza)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LblOlvideContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(chterminos)
                        .addGap(1, 1, 1)
                        .addComponent(lblterminos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(chdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblHospital)
                        .addGap(2, 2, 2)
                        .addComponent(LblLoayza)))
                .addGap(20, 20, 20)
                .addComponent(lbltitulo)
                .addGap(42, 42, 42)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblcontraseña)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblOlvideContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chterminos)
                    .addComponent(lblterminos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(chdatos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Background)
        );

        lblterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblterminos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    // Reemplaza el link con el de tu sitio o archivo
                    java.awt.Desktop.getDesktop().browse(new java.net.URI("https://cdn.www.gob.pe/uploads/document/file/6097137/5393559-r-a-n-191-2024-hnal-op.pdf"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        pack();
    }//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String usuario = txtusuario.getText();
        String contraseña = new String(txtcontraseña.getPassword());
        if(!chterminos.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe aceptar los Términos y Condiciones.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!chdatos.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe aceptar el tratamiento de datos personales.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (login.iniciarSesion(usuario, contraseña)) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
            this.dispose();
            FormMenu_Hospital menu = new FormMenu_Hospital();
            menu.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void LblOlvideContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblOlvideContraseñaMouseClicked
        FormRecuperacionContraseña recuperar = new FormRecuperacionContraseña(login.LecturaJsonUsuarios(txtusuario.getText()));
        recuperar.setVisible(true);
    }//GEN-LAST:event_LblOlvideContraseñaMouseClicked

    private void JLabelMouseEncima(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelMouseEncima
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.BLUE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_JLabelMouseEncima

    private void JLabelMouseSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelMouseSalir
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (0,0,0));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        }
    }//GEN-LAST:event_JLabelMouseSalir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblOlvideContraseña;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JCheckBox chdatos;
    private javax.swing.JCheckBox chterminos;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblterminos;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
