/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JLabel;
import javax.swing.JEditorPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;



public class LoginForm extends javax.swing.JFrame {

   
   
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        chterminos = new javax.swing.JCheckBox();
        chdatos = new javax.swing.JCheckBox();
        lblterminos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblusuario.setText("Usuario:");

        lblcontraseña.setText("Contraseña:");

        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRecuperar.setText("¿Olvidaste tu contraseña?");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltitulo.setText("INICIAR SESION");

        chterminos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chterminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chterminosActionPerformed(evt);
            }
        });

        chdatos.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        chdatos.setText("HE LEÍDO Y ACEPTO EL TRATAMIENTO DE MIS DATOS PERSONALES PARA FINALIDADES ADICONALES");
        chdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chdatosActionPerformed(evt);
            }
        });

        lblterminos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblterminos.setText("TERMINOS Y CONDICIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnIniciarSesion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblusuario)
                                .addComponent(lbltitulo)
                                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcontraseña)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRecuperar))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chdatos)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chterminos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblterminos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lbltitulo)
                .addGap(35, 35, 35)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcontraseña)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecuperar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblterminos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chterminos))
                .addGap(18, 18, 18)
                .addComponent(chdatos)
                .addGap(71, 71, 71)
                .addComponent(btnIniciarSesion)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        lblterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblterminos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    // Reemplaza el link con el de tu sitio o archivo
                    java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.youtube.com/"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String usuario = txtusuario.getText();
        String contraseña = new String(txtcontraseña.getPassword());
        
        
        if(!chterminos.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe aceptar los Términos y Condiciones.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!chdatos.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe aceptar el tratamiento de datos personales.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (usuario.equals("admin") && contraseña.equals("1234")) {
        JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
        // Aquí puedes abrir la siguiente ventana, por ejemplo
    } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        //login login = new login();
            //if (login.iniciarSesion(txtusuario.getText(), new String(txtcontraseña.getPassword()))) {
            //JOptionPane.showMessageDialog(this, "Bienvenido al sistema", "Acceso Concedido", JOptionPane.INFORMATION_MESSAGE);
       // }//
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void chterminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chterminosActionPerformed
        
            
    }//GEN-LAST:event_chterminosActionPerformed

    private void chdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chdatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chdatosActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        login login = new login();
        login.recuperarContraseña(txtusuario.getText());
    }//GEN-LAST:event_btnRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JCheckBox chdatos;
    private javax.swing.JCheckBox chterminos;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblterminos;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
