/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;

import javax.swing.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;



public class LoginForm extends javax.swing.JFrame {
    
    Login login = new Login();
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();
        chterminos = new javax.swing.JCheckBox();
        chdatos = new javax.swing.JCheckBox();
        lblterminos = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblOlvideContraseña = new javax.swing.JLabel();
        btnIniciarSesion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 90));

        lblusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblusuario.setText("USUARIO");
        getContentPane().add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 20));

        lblcontraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblcontraseña.setText("CONTRASEÑA");
        getContentPane().add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, -1));

        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 430, 37));

        txtcontraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 430, 34));

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 300, 70));

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setText("ACCEDE AL SISTEMA");
        getContentPane().add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 330, -1));

        chterminos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chterminos.setForeground(new java.awt.Color(255, 255, 255));
        chterminos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(chterminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        chdatos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chdatos.setText("<html>HE LEÍDO Y ACEPTO EL TRATAMIENTO DE MIS DATOS PERSONALES<br>PARA FINALIDADES ADICONALES<html>");
        chdatos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(chdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 480, 60));

        lblterminos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblterminos.setText("<html><u>TERMINOS Y CONDICIONES</u></html>");
        lblterminos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelMouseEncima(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelMouseSalir(evt);
            }
        });
        getContentPane().add(lblterminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 190, -1));
        lblterminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblterminos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                try {
                    // Reemplaza el link con el de tu sitio o archivo
                    java.awt.Desktop.getDesktop().browse(new java.net.URI("https://cdn.www.gob.pe/uploads/document/file/6097137/5393559-r-a-n-191-2024-hnal-op.pdf"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/banner.jpeg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 430, -1));

        LblLoayza.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(255, 39, 40));
        LblLoayza.setText("LOAYZA NACIONAL");
        getContentPane().add(LblLoayza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 52, -1, -1));

        LblHospital.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");
        getContentPane().add(LblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        LblOlvideContraseña.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LblOlvideContraseña.setText("<html><u>OLVIDE MI<br>CONTRASEÑA</u></html>");
        LblOlvideContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblOlvideContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelMouseEncima(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelMouseSalir(evt);
            }
        });
        getContentPane().add(LblOlvideContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 100, 40));

        btnIniciarSesion1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarSesion1.setText("INICIAR SESION");
        btnIniciarSesion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 300, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String usuario = txtusuario.getText();
        String contraseña = new String(txtcontraseña.getPassword());
        
        
        String rol=Login.iniciarSesion(usuario, contraseña);
        
        if(rol != null)
        {
            JOptionPane.showMessageDialog(null,"Bienvenido: " +rol);
            switch(rol){
        case "Administrador":
            new FormMenu_Hospital().setVisible(true);
            break;
        case "Auditor":
            new FormAuditor().setVisible(true);
            break;
        case "Supervisor":
            new FormSupervisor().setVisible(true);;
            break;
        default:
            new FormMedico().setVisible(true);;
            break;
        }
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
        }
                
            
        /*
        if(!chterminos.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe aceptar los Términos y Condiciones.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!chdatos.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe aceptar el tratamiento de datos personales.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (login.iniciarSesion(usuario, contraseña)) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso. \n(Usted ingreso como " + login.rolusuario + ")");
            this.dispose();
            FormMenu_Hospital menu = new FormMenu_Hospital();
            menu.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void LblOlvideContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblOlvideContraseñaMouseClicked
        FormRecuperacionContraseña recuperar = new FormRecuperacionContraseña(login.LecturaJsonUsuarios(txtusuario.getText()));
        recuperar.setVisible(true);
    }//GEN-LAST:event_LblOlvideContraseñaMouseClicked

    private void JLabelMouseEncima(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelMouseEncima
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.BLUE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_JLabelMouseEncima

    private void JLabelMouseSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelMouseSalir
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (0,0,0));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        }
    }//GEN-LAST:event_JLabelMouseSalir

    private void btnIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblOlvideContraseña;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JCheckBox chdatos;
    private javax.swing.JCheckBox chterminos;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblterminos;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
