/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
/**
 *
 * @author Alexis
 */
public class Menu_Hospital extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Hospital
     */
    public Menu_Hospital() {
        initComponents();
        this.setLocationRelativeTo(null);
        BtnAgendar.setBorder(new CompoundBorder(
                new LineBorder(Color.BLUE,5,true),
                new EmptyBorder(10,20,10,20)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        IconMenu = new javax.swing.JLabel();
        BackgroundMenu = new javax.swing.JLabel();
        wsp = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblNumero1 = new javax.swing.JLabel();
        LblContacto = new javax.swing.JLabel();
        LblNumero3 = new javax.swing.JLabel();
        LblPacientes = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblMedicos = new javax.swing.JLabel();
        LblExamenes = new javax.swing.JLabel();
        LblCitas = new javax.swing.JLabel();
        BtnAgendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N
        IconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BackgroundMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexis\\Documents\\GitHub\\Gestor-de-Citas-HL\\src\\gestion\\administrativa\\hospital\\la\\menu.jpeg")); // NOI18N

        wsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/wsp.png"))); // NOI18N

        LblLoayza.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(236, 31, 54));
        LblLoayza.setText("LOAYZA NACIONAL");

        LblNumero1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero1.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero1.setText("4800");

        LblContacto.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LblContacto.setForeground(new java.awt.Color(6, 5, 235));
        LblContacto.setText("CONTACTO");

        LblNumero3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero3.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero3.setText("509");

        LblPacientes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblPacientes.setForeground(new java.awt.Color(6, 5, 235));
        LblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPacientes.setText("Pacientes");
        LblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMouseSalirOpciones(evt);
            }
        });

        LblHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");

        LblMedicos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblMedicos.setForeground(new java.awt.Color(6, 5, 235));
        LblMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMedicos.setText("Médicos");
        LblMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMedicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMouseSalirOpciones(evt);
            }
        });

        LblExamenes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblExamenes.setForeground(new java.awt.Color(48, 73, 101));
        LblExamenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblExamenes.setText("Exámenes");

        LblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblCitas.setForeground(new java.awt.Color(48, 73, 101));
        LblCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCitas.setText("Citas médicas activas");

        BtnAgendar.setBackground(new java.awt.Color(0, 74, 173));
        BtnAgendar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgendar.setText("<html>AGENDAR<br>CITAS</html>");
        BtnAgendar.setToolTipText("");
        BtnAgendar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 173), 0, true));
        BtnAgendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgendar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IconMenu)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHospital)
                    .addComponent(LblLoayza))
                .addGap(24, 24, 24)
                .addComponent(LblContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(wsp)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNumero3))
                .addGap(20, 20, 20)
                .addComponent(BtnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LblExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LblCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(LblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BackgroundMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblHospital)
                        .addGap(6, 6, 6)
                        .addComponent(LblLoayza))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LblContacto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(wsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LblNumero1))
                            .addComponent(LblNumero3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BtnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(BackgroundMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }//GEN-END:initComponents

    private void LblMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblMedicosMouseClicked

    private void LblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblPacientesMouseClicked

    private void LblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblMouseEncimaOpciones

    private void LblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        
        }
    }//GEN-LAST:event_LblMouseSalirOpciones

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMenu;
    private javax.swing.JButton BtnAgendar;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel LblCitas;
    private javax.swing.JLabel LblContacto;
    private javax.swing.JLabel LblExamenes;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblMedicos;
    private javax.swing.JLabel LblNumero1;
    private javax.swing.JLabel LblNumero3;
    private javax.swing.JLabel LblPacientes;
    private javax.swing.JLabel wsp;
    // End of variables declaration//GEN-END:variables
}
