/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class PacientesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PacientesForm.class.getName());

    /**
     * Creates new form frmprincipal
     */
    public PacientesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{
                "Nombre", "DNI", "Teléfono", "Género", "Fecha Nac.",
                "Alergias", "Enfermedades", "Tipo Sangre", "Notas",
                "Última Atención", "Diagnóstico", "Tratamiento",
                "Médico", "Próxima Cita"
});
tblinformacion.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblID = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtBuscar1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinformacion = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LblTitulo.setFont(new java.awt.Font("Lilita One", 1, 48)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("PACIENTES REGISTROS");
        getContentPane().add(LblTitulo);
        LblTitulo.setBounds(50, 20, 530, 50);

        LblNombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(0, 0, 0));
        LblNombre.setText("NOMBRE");
        getContentPane().add(LblNombre);
        LblNombre.setBounds(60, 160, 110, 30);

        LblID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        LblID.setForeground(new java.awt.Color(0, 0, 0));
        LblID.setText("ID");
        getContentPane().add(LblID);
        LblID.setBounds(60, 100, 30, 40);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(180, 150, 270, 39);

        txtBuscar1.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar1.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtBuscar1);
        txtBuscar1.setBounds(180, 90, 270, 39);

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(500, 110, 180, 60);

        tblinformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRES Y APELLIDOS", "INFORMACIÓN"
            }
        ));
        jScrollPane1.setViewportView(tblinformacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(59, 290, 620, 180);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/background.jpeg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 730, 500);

        pack();
    }//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String valor = txtBuscar.getText().trim();
    String ruta = "data/pacientes.json"; // ajusta si está en otra ubicación

    buscar paciente = metodosbuscar.buscarpaciente(valor, ruta);

    DefaultTableModel modelo = (DefaultTableModel) tblinformacion.getModel();
    modelo.setRowCount(0); // limpiar tabla

    if (paciente != null) {
        modelo.addRow(new Object[]{
            paciente.getNombres(),
            paciente.getDNI(),
            paciente.getMedico(),
            paciente.getUltimaAtencion(),
            paciente.getProximaCita()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Paciente no encontrado");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PacientesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinformacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    // End of variables declaration//GEN-END:variables
}
