/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;

import javax.swing.*;
import java.awt.BorderLayout;

import java.nio.file.Files;
import java.nio.file.Paths;

import org.json.JSONObject;
import org.json.JSONArray;

/**
 *
 * @author Alexis
 */
public class PanelPacientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelPacientes
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelPacientes.class.getName());
    private JPanel contenedor;
    
    public PanelPacientes(JPanel content) {
        initComponents();
        contenedor = content;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        lblMedicos = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblID = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinformacion = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedicos.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMedicos.setForeground(new java.awt.Color(8, 79, 176));
        lblMedicos.setText("PACIENTES");
        lblMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 79, 176), 3));
        lblMedicos.setOpaque(true);
        add(lblMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 610, 60));

        LblTitulo.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setText("PACIENTES REGISTROS");
        add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 439, 50));

        LblNombre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(0, 0, 0));
        LblNombre.setText("NOMBRE");
        add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 30));

        LblID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        LblID.setForeground(new java.awt.Color(0, 0, 0));
        LblID.setText("ID");
        add(LblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 30, 40));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 280, 39));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 280, 39));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 180, 50));

        tblinformacion.setBackground(new java.awt.Color(255, 255, 255));
        tblinformacion.setForeground(new java.awt.Color(0, 0, 0));
        tblinformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRES Y APELLIDOS", "INFORMACIÓN"
            }
        ));
        jScrollPane1.setViewportView(tblinformacion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 610, 200));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 50));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 180, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/background.jpeg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));
    }//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Pacientes pacientes = new Pacientes();
        pacientes.BuscarYMostrarPacientes(tblinformacion, txtID, txtBuscar);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Pacientes pacientes = new Pacientes();
        String id = tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 0).toString();
        pacientes.EditarPaciente(id, contenedor);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Pacientes pacientes = new Pacientes();
        String id = tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 0).toString();
        pacientes.EliminarPaciente(id);
        int opcion = JOptionPane.showOptionDialog(
                    this,
                    "¿Estas seguro que deseas eliminar a" + tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 1).toString() + "?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[] { "Si", "No" },  // Opciones personalizadas
                    "Sí"
                );
        if (opcion == JOptionPane.YES_OPTION){
            pacientes.EliminarPaciente(id);
            JOptionPane.showMessageDialog(null, "Se eliminó al paciente correspondite con éxito.", "¡Eliminado!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicos;
    private javax.swing.JTable tblinformacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
