/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;

import java.awt.Color;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Alexis
 */
public class PanelMenu_Hospital extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenu_Hospital
     */
    public PanelMenu_Hospital() {
        initComponents();
        BtnAgendar.setBorder(new CompoundBorder(
                new LineBorder(Color.BLUE,5,true),
                new EmptyBorder(10,20,10,20)
        ));
        FontIcon icon = FontIcon.of(FontAwesomeSolid.CALENDAR, 35);
        icon.setIconColor(java.awt.Color.WHITE);
        BtnAgendar.setIcon(icon);
        BtnAgendar.setHorizontalTextPosition(SwingConstants.RIGHT);
        BtnAgendar.setVerticalTextPosition(SwingConstants.CENTER);
        BtnAgendar.setHorizontalAlignment(SwingConstants.LEFT);
        BtnAgendar.setHorizontalTextPosition(SwingConstants.RIGHT);
        BtnAgendar.setIconTextGap(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        content = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        BackgroundMenu = new javax.swing.JLabel();
        wsp = new javax.swing.JLabel();
        LblLoayza = new javax.swing.JLabel();
        LblNumero1 = new javax.swing.JLabel();
        LblContacto = new javax.swing.JLabel();
        LblNumero3 = new javax.swing.JLabel();
        LblPacientes = new javax.swing.JLabel();
        LblHospital = new javax.swing.JLabel();
        LblMedicos = new javax.swing.JLabel();
        LblExamenes = new javax.swing.JLabel();
        LblCitas = new javax.swing.JLabel();
        BtnAgendar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/logo.jpeg"))); // NOI18N
        IconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        content.add(IconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 82));

        BackgroundMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexis\\Documents\\GitHub\\Gestor-de-Citas-HL\\src\\gestion\\administrativa\\hospital\\la\\menu.jpeg")); // NOI18N
        content.add(BackgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 730, 350));

        wsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/wsp.png"))); // NOI18N
        content.add(wsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 40, -1, 30));

        LblLoayza.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblLoayza.setForeground(new java.awt.Color(236, 31, 54));
        LblLoayza.setText("LOAYZA NACIONAL");
        content.add(LblLoayza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        LblNumero1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero1.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero1.setText("4800");
        content.add(LblNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 50, 60, -1));

        LblContacto.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LblContacto.setForeground(new java.awt.Color(6, 5, 235));
        LblContacto.setText("CONTACTO");
        content.add(LblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 40, 100, -1));

        LblNumero3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblNumero3.setForeground(new java.awt.Color(6, 5, 235));
        LblNumero3.setText("509");
        content.add(LblNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 20, -1, -1));

        LblPacientes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblPacientes.setForeground(new java.awt.Color(6, 5, 235));
        LblPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPacientes.setText("Pacientes");
        LblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblPacientesLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 140, 150, 40));

        LblHospital.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblHospital.setForeground(new java.awt.Color(6, 5, 235));
        LblHospital.setText("HOSPITAL ARZOBISPO");
        content.add(LblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        LblMedicos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblMedicos.setForeground(new java.awt.Color(6, 5, 235));
        LblMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMedicos.setText("Médicos");
        LblMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMedicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMedicosLblMouseEncimaOpciones(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMedicosLblMouseSalirOpciones(evt);
            }
        });
        content.add(LblMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, 150, 40));

        LblExamenes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblExamenes.setForeground(new java.awt.Color(48, 73, 101));
        LblExamenes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblExamenes.setText("Exámenes");
        content.add(LblExamenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 140, 150, 40));

        LblCitas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LblCitas.setForeground(new java.awt.Color(48, 73, 101));
        LblCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCitas.setText("Citas médicas activas");
        content.add(LblCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 140, 270, 40));

        BtnAgendar.setBackground(new java.awt.Color(0, 74, 173));
        BtnAgendar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgendar.setText("<html>AGENDAR<br>CITAS</html>");
        BtnAgendar.setToolTipText("");
        BtnAgendar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 74, 173), 0, true));
        BtnAgendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgendar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BtnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgendarActionPerformed(evt);
            }
        });
        content.add(BtnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 20, 140, 70));

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }//GEN-END:initComponents

    private void LblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesMouseClicked
        PanelPacientes pacientes = new PanelPacientes();
        pacientes.setSize(740, 530);
        pacientes.setLocation(0,0);

        content.setLayout(new BorderLayout());
        content.removeAll();
        content.add(pacientes, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_LblPacientesMouseClicked

    private void LblPacientesLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblPacientesLblMouseEncimaOpciones

    private void LblPacientesLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPacientesLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblPacientesLblMouseSalirOpciones

    private void LblMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosMouseClicked
        PanelMedicos medicos = new PanelMedicos();
        medicos.setSize(740, 530);
        medicos.setLocation(0,0);

        content.setLayout(new BorderLayout());
        content.removeAll();
        content.add(medicos, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_LblMedicosMouseClicked

    private void LblMedicosLblMouseEncimaOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosLblMouseEncimaOpciones
        Object fuente = evt.getSource();
        if (fuente instanceof JLabel){
            JLabel label = (JLabel) fuente;
            label.setForeground(Color.WHITE);
            label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_LblMedicosLblMouseEncimaOpciones

    private void LblMedicosLblMouseSalirOpciones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMedicosLblMouseSalirOpciones
        if (evt.getSource() instanceof JComponent componente){
            componente.setForeground(new Color (6,5,235));
            componente.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

        }
    }//GEN-LAST:event_LblMedicosLblMouseSalirOpciones

    private void BtnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgendarActionPerformed
        PanelRegistrodeCitas registros = new PanelRegistrodeCitas();
        registros.setSize(740, 530);
        registros.setLocation(0,0);

        content.setLayout(new BorderLayout());
        content.removeAll();
        content.add(registros, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_BtnAgendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundMenu;
    private javax.swing.JButton BtnAgendar;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel LblCitas;
    private javax.swing.JLabel LblContacto;
    private javax.swing.JLabel LblExamenes;
    private javax.swing.JLabel LblHospital;
    private javax.swing.JLabel LblLoayza;
    private javax.swing.JLabel LblMedicos;
    private javax.swing.JLabel LblNumero1;
    private javax.swing.JLabel LblNumero3;
    private javax.swing.JLabel LblPacientes;
    private javax.swing.JPanel content;
    private javax.swing.JLabel wsp;
    // End of variables declaration//GEN-END:variables
}
