/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;

import javax.swing.*;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import java.awt.*;
import javax.swing.JOptionPane;
import java.awt.Component;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Alexis
 */
public class PanelPacientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelPacientes
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelPacientes.class.getName());
    private JPanel contenedor;
    FontIcon icon = FontIcon.of(FontAwesomeSolid.CHEVRON_LEFT, 35);
    
    public PanelPacientes(JPanel content) {
        initComponents();
        contenedor = content;
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setIcon(icon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        lblMedicos = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblID = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinformacion = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedicos.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMedicos.setForeground(new java.awt.Color(8, 79, 176));
        lblMedicos.setText("PACIENTES");
        lblMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 79, 176), 3));
        lblMedicos.setOpaque(true);
        add(lblMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 610, 60));

        LblTitulo.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setText("PACIENTES REGISTRADOS");
        add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 500, 50));

        LblNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(0, 0, 0));
        LblNombre.setText("NOMBRE");
        add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, 30));

        LblID.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        LblID.setForeground(new java.awt.Color(0, 0, 0));
        LblID.setText("ID");
        add(LblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 30, 40));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 270, 39));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 270, 39));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 180, 50));

        tblinformacion.setBackground(new java.awt.Color(255, 255, 255));
        tblinformacion.setForeground(new java.awt.Color(0, 0, 0));
        tblinformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRES Y APELLIDOS", "INFORMACIÓN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblinformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblinformacion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 610, 200));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 50));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 180, 50));

        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/paciente-registro.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));
    }//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Pacientes pacientes = new Pacientes();
        pacientes.BuscarYMostrarPacientes(tblinformacion, txtID, txtBuscar);
        tblinformacion.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                   boolean isSelected, boolean hasFocus,
                                                   int row, int column) {
                JTextArea area = new JTextArea();
                area.setText(value != null ? value.toString() : "");
                area.setWrapStyleWord(true);
                area.setLineWrap(true);
                area.setOpaque(true);
                area.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                area.setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
                return area;
            }
        });
        tblinformacion.setRowHeight(80);
        tblinformacion.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblinformacion.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblinformacion.getColumnModel().getColumn(2).setPreferredWidth(300);
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        tblinformacion.getColumnModel().getColumn(1).setCellRenderer(centrado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Pacientes pacientes = new Pacientes();
        String id = tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 0).toString();
        pacientes.EditarPaciente(id, contenedor);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Pacientes pacientes = new Pacientes();
        String id = tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 0).toString();
        pacientes.EliminarPaciente(id);
        int opcion = JOptionPane.showOptionDialog(
                    this,
                    "¿Estas seguro que deseas eliminar a" + tblinformacion.getValueAt(tblinformacion.getSelectedRow(), 1).toString() + "?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[] { "Si", "No" },  // Opciones personalizadas
                    "Sí"
                );
        if (opcion == JOptionPane.YES_OPTION){
            pacientes.EliminarPaciente(id);
            JOptionPane.showMessageDialog(null, "Se eliminó al paciente correspondite con éxito.", "¡Eliminado!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        PanelMenu_Hospital medicos_registro = new PanelMenu_Hospital();
        medicos_registro.setSize(740, 530);
        medicos_registro.setLocation(0,0);
        contenedor.setLayout(new BorderLayout());
        contenedor.removeAll();
        contenedor.add(medicos_registro, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        icon.setIconColor(java.awt.Color.WHITE);
        BotonRegresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel LblID;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicos;
    private javax.swing.JTable tblinformacion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
