/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;

import java.awt.BorderLayout;
import java.awt.Color;
import org.json.JSONObject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

/**
 *
 * @author Alexis
 */
public class PanelMedicos extends javax.swing.JPanel {

    /**
     * Creates new form PanelMedicos
     */
    
    private BaseMedicos base_de_datos = new BaseMedicos("src/gestion/administrativa/hospital/la/medicos.json");
    public PanelMedicos() {
        initComponents();
        jScrollPane2.setBackground(Color.red);
        TblMedicos.getColumnModel().getColumn(0).setPreferredWidth(250);   // ID
        TblMedicos.getColumnModel().getColumn(1).setPreferredWidth(150);  // Nombres y Apellidos
        TblMedicos.getColumnModel().getColumn(2).setPreferredWidth(80);  // Especialidad
        TblMedicos.getColumnModel().getColumn(3).setPreferredWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        lblTitulo = new javax.swing.JLabel();
        sublblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblMedicos = new javax.swing.JTable();
        TxfFNombre = new javax.swing.JTextField();
        lblMedicos = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Chewy", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(57, 74, 130));
        lblTitulo.setText("MEDICOS");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        sublblTitulo.setFont(new java.awt.Font("Chewy", 1, 36)); // NOI18N
        sublblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        sublblTitulo.setText("MEDICOS");
        add(sublblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, 54));

        LblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(0, 0, 0));
        LblNombre.setText("Nombre:");
        add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 160, 50));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR CITA");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 190, 50));

        TblMedicos.setBackground(new java.awt.Color(255, 255, 255));
        TblMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 79, 176), 3));
        TblMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRES Y APELLIDOS", "CONTACTO", "ESPECIALIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblMedicos.setEnabled(false);
        TblMedicos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TblMedicos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 680, 240));

        TxfFNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxfFNombre.setForeground(new java.awt.Color(0, 0, 0));
        add(TxfFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 350, 30));

        lblMedicos.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMedicos.setForeground(new java.awt.Color(8, 79, 176));
        lblMedicos.setText(" MEDICOS");
        lblMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 79, 176), 3));
        lblMedicos.setOpaque(true);
        add(lblMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 680, 60));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/background.jpeg"))); // NOI18N
        Background.setText("jLabel1");
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));
    }//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        base_de_datos.MostrarTablaMedicos(TxfFNombre, TblMedicos);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        PanelRegistrodeCitas registros = new PanelRegistrodeCitas();
        registros.setSize(740, 530);
        registros.setLocation(0,0);
        
        this.setLayout(new BorderLayout());
        this.removeAll();
        this.add(registros, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JTable TblMedicos;
    private javax.swing.JTextField TxfFNombre;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMedicos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel sublblTitulo;
    // End of variables declaration//GEN-END:variables
}
