/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;
import java.util.Date;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;

import java.awt.*;
import javax.swing.JOptionPane;
import java.awt.Component;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
/**
 *
 * @author Alexis
 */
public class PanelRegistroPacientes extends javax.swing.JPanel {

    JDateChooser dateChooser = new JDateChooser();
    private JPanel contenedor;
    FontIcon icon = FontIcon.of(FontAwesomeSolid.CHEVRON_LEFT, 35);
    /**
     * Creates new form PanelRegistroPacientesd
     */
    public PanelRegistroPacientes(JPanel content) {
        initComponents();
        contenedor = content;
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setIcon(icon);
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 210, 30));
        dateChooser.getDateEditor().setEnabled(false);
        dateChooser.getDateEditor().getUiComponent().setForeground(Color.BLACK);
        dateChooser.setBorder(new LineBorder(Color.BLUE, 2));
        
        setComponentZOrder(dateChooser, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        LblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBSangre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtFDNI = new javax.swing.JTextField();
        TxtFTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFEnfermedadesCronicas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtFNotasMedicas = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtFAlergias = new javax.swing.JTextField();
        BotonRegresar = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTitulo.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setText("REGISTRO DE PACIENTES");
        add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 480, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRES COMPLETOS:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        TxtFNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxtFNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxtFNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA DE NACIMIENTO:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("GÉNERO:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        CBSangre.setBackground(new java.awt.Color(255, 255, 255));
        CBSangre.setForeground(new java.awt.Color(0, 0, 0));
        CBSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------------------", "A+", "A−", "B+", "B−", "AB+", "AB−", "O+", " O−" }));
        CBSangre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(CBSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 210, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        TxtFDNI.setBackground(new java.awt.Color(255, 255, 255));
        TxtFDNI.setForeground(new java.awt.Color(0, 0, 0));
        TxtFDNI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 210, 30));

        TxtFTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TxtFTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TxtFTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 210, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TELÉFONO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        TxtFEnfermedadesCronicas.setBackground(new java.awt.Color(255, 255, 255));
        TxtFEnfermedadesCronicas.setForeground(new java.awt.Color(0, 0, 0));
        TxtFEnfermedadesCronicas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFEnfermedadesCronicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ENFERMEDADES CRONICAS:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        CBGenero.setBackground(new java.awt.Color(255, 255, 255));
        CBGenero.setForeground(new java.awt.Color(0, 0, 0));
        CBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------------------", "Masculino", "Femenino" }));
        CBGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(CBGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 210, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TIPO DE SANGRE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("NOTAS MÉDICAS URGENTES:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        TxtFNotasMedicas.setBackground(new java.awt.Color(255, 255, 255));
        TxtFNotasMedicas.setForeground(new java.awt.Color(0, 0, 0));
        TxtFNotasMedicas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFNotasMedicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 210, 30));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 150, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ALERGIAS:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        TxtFAlergias.setBackground(new java.awt.Color(255, 255, 255));
        TxtFAlergias.setForeground(new java.awt.Color(0, 0, 0));
        TxtFAlergias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 210, 30));

        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/registrar-pacientes.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));
    }//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Pacientes pacientes = new Pacientes();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = dateChooser.getDate();
        String nombre = TxtFNombre.getText().trim();
        String genero = CBGenero.getSelectedItem().toString();
        String dni = TxtFDNI.getText().trim();
        String telefono = TxtFTelefono.getText().trim();
        String alergias = TxtFAlergias.getText().trim();
        String enfermedades = TxtFEnfermedadesCronicas.getText().trim();
        String sangre = CBSangre.getSelectedItem().toString();
        String notas = TxtFNotasMedicas.getText().trim();
        if (nombre.isEmpty() || fecha == null || genero.isEmpty() || dni.isEmpty() || telefono.isEmpty() ||
            alergias.isEmpty() || enfermedades.isEmpty() || sangre.isEmpty() || notas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!dni.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(null, "El DNI debe tener exactamente 8 dígitos numéricos.", "DNI inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!telefono.matches("0\\d{8}")) {
            JOptionPane.showMessageDialog(null, "El teléfono debe tener 9 dígitos y comenzar con 0.", "Teléfono inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pacientes.RegistrarNuevosPacientes(TxtFNombre.getText(), 
                                            formato.format(fecha), 
                                            CBGenero.getSelectedItem().toString(), 
                                            TxtFDNI.getText(), 
                                            TxtFTelefono.getText(), 
                                            TxtFAlergias.getText(), 
                                            TxtFEnfermedadesCronicas.getText(), 
                                            CBSangre.getSelectedItem().toString(), 
                                            TxtFNotasMedicas.getText(), 
                                            pacientes.generarIDAlfanumerico());
        JOptionPane.showMessageDialog(null, "Paciente registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        PanelMenu_Hospital medicos_registro = new PanelMenu_Hospital();
        medicos_registro.setSize(740, 530);
        medicos_registro.setLocation(0,0);
        contenedor.setLayout(new BorderLayout());
        contenedor.removeAll();
        contenedor.add(medicos_registro, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        icon.setIconColor(java.awt.Color.WHITE);
        BotonRegresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JComboBox<String> CBGenero;
    private javax.swing.JComboBox<String> CBSangre;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtFAlergias;
    private javax.swing.JTextField TxtFDNI;
    private javax.swing.JTextField TxtFEnfermedadesCronicas;
    private javax.swing.JTextField TxtFNombre;
    private javax.swing.JTextField TxtFNotasMedicas;
    private javax.swing.JTextField TxtFTelefono;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
