/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;
import org.json.JSONObject;
import javax.swing.*;
import java.util.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.awt.BorderLayout;
import java.awt.Cursor;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
/**
 *
 * @author Alexis
 */
public class PanelRegistrodeCitas extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrodeCitas
     */
    private BaseMedicos base_de_datos = new BaseMedicos("src/gestion/administrativa/hospital/la/medicos.json");
    private Pacientes paciente = new Pacientes();
    private List<JSONObject> listaMedicos;
    private JPanel contenedor;
    FontIcon icon = FontIcon.of(FontAwesomeSolid.CHEVRON_LEFT, 35);
    public PanelRegistrodeCitas(JPanel content) {
        initComponents();
        contenedor = content;
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setIcon(icon);
        base_de_datos.llenarComboEspecialidades(CB_Especialidad);
        paciente.CargarNombresMedicos(CB_Paciente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        Lbl_Titulo = new javax.swing.JLabel();
        lbl_especialidad = new javax.swing.JLabel();
        CB_Médicos = new javax.swing.JComboBox<>();
        CB_Especialidad = new javax.swing.JComboBox<>();
        BtnConfirmar = new javax.swing.JButton();
        lbl_especialidad1 = new javax.swing.JLabel();
        lbl_paciente = new javax.swing.JLabel();
        CB_Paciente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Médico = new javax.swing.JTable();
        BotonRegresar = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Titulo.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        Lbl_Titulo.setForeground(new java.awt.Color(57, 74, 128));
        Lbl_Titulo.setText("Registro de Citas");
        add(Lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 6, 460, -1));

        lbl_especialidad.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_especialidad.setForeground(new java.awt.Color(0, 0, 0));
        lbl_especialidad.setText("Médico:");
        add(lbl_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 80, -1));

        CB_Médicos.setBackground(new java.awt.Color(255, 255, 255));
        CB_Médicos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Médicos.setForeground(new java.awt.Color(0, 0, 0));
        CB_Médicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Médicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        CB_Médicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_MédicosItemStateChanged(evt);
            }
        });
        add(CB_Médicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 39));

        CB_Especialidad.setBackground(new java.awt.Color(255, 255, 255));
        CB_Especialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Especialidad.setForeground(new java.awt.Color(0, 0, 0));
        CB_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Especialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        CB_Especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_EspecialidadItemStateChanged(evt);
            }
        });
        add(CB_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 39));

        BtnConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setText("CONFIRMAR");
        BtnConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });
        add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 170, 50));

        lbl_especialidad1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_especialidad1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_especialidad1.setText("Especialidad:");
        add(lbl_especialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, -1, -1));

        lbl_paciente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_paciente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_paciente.setText("Paciente:");
        add(lbl_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        CB_Paciente.setBackground(new java.awt.Color(255, 255, 255));
        CB_Paciente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Paciente.setForeground(new java.awt.Color(0, 0, 0));
        CB_Paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Paciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        add(CB_Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 220, 39));

        Tabla_Médico.setBackground(new java.awt.Color(255, 255, 255));
        Tabla_Médico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla_Médico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos y Nombres", "ID", "Fecha", "Hora", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_Médico);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 145, 680, 300));

        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/registro-citas.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 530));
    }//GEN-END:initComponents

    public static void guardarFilaSeleccionada(JTable tabla) {
        int filaSeleccionada = tabla.getSelectedRow();

        if (filaSeleccionada == -1) {
            System.out.println("No hay fila seleccionada.");
            return;
        }

        try {
            String rutaProyecto = System.getProperty("user.dir");
            String rutaArchivo = rutaProyecto + "/citas.txt";

            File archivo = new File(rutaArchivo);

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo, true))) {
                for (int columna = 0; columna < tabla.getColumnCount(); columna++) {
                    Object valorCelda = tabla.getValueAt(filaSeleccionada, columna);
                    writer.write(valorCelda != null ? valorCelda.toString() : "");
                    writer.newLine();
                }
                writer.newLine();
            }

            System.out.println("Archivo guardado en: " + rutaArchivo);
        } catch (IOException e) {
            System.out.println("Error al guardar el archivo: " + e.getMessage());
        }
    }
    
    public void llenarComboMedicosPorEspecialidad(JComboBox<String> combo, String especialidad) {
    combo.removeAllItems();
    for (JSONObject medico : listaMedicos) {
        if (medico.getString("especialidad").equals(especialidad)) {
            combo.addItem(medico.getString("nombre"));
        }
    }
}
    
    private void CB_MédicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_MédicosItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String medicoSeleccionado = (String) CB_Médicos.getSelectedItem();
            base_de_datos.llenarTablaMedicoSeleccionado(Tabla_Médico, medicoSeleccionado);
        }
    }//GEN-LAST:event_CB_MédicosItemStateChanged

    private void CB_EspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_EspecialidadItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            String especialidadSeleccionada = (String) CB_Especialidad.getSelectedItem();
            base_de_datos.llenarComboMedicos(CB_Médicos, CB_Especialidad.getSelectedItem().toString());
        }
    }//GEN-LAST:event_CB_EspecialidadItemStateChanged

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        int filaSeleccionada = Tabla_Médico.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un médico de la tabla.", "Médico no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nom_paciente = (String) CB_Paciente.getSelectedItem();
        if (nom_paciente == null || nom_paciente.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un paciente del combo box.", "Paciente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        guardarFilaSeleccionada(Tabla_Médico);
        Ticket ticket = new Ticket();
        String nom_medico = Tabla_Médico.getValueAt(Tabla_Médico.getSelectedRow(), 0).toString();
        String id_medico = Tabla_Médico.getValueAt(Tabla_Médico.getSelectedRow(), 1).toString();
        String hora_medico = Tabla_Médico.getValueAt(Tabla_Médico.getSelectedRow(), 2).toString();
        String dia_medico = Tabla_Médico.getValueAt(Tabla_Médico.getSelectedRow(), 3).toString();
        String horario_medico = hora_medico + " / " + dia_medico;
        String especialidad = Tabla_Médico.getValueAt(Tabla_Médico.getSelectedRow(), 4).toString();
        String id_paciente = ticket.ObtenerIDPaciente(nom_paciente);
        boolean generarticket = ticket.RegistrarNuevaCita(nom_medico, id_medico, dia_medico, hora_medico, especialidad, nom_paciente, id_paciente);
        if (generarticket){
            //Mensaje de que se creo un ticket
            ticket.generarCitaPDF(nom_paciente, id_paciente, horario_medico, especialidad, nom_medico, ticket.CantidadCitas(), "src/gestion/administrativa/hospital/la/ticket/ticket" + String.format("%03d", ticket.CantidadCitas()) + ".pdf");
        }
        String medicoSeleccionado = (String) CB_Médicos.getSelectedItem();
        base_de_datos.llenarTablaMedicoSeleccionado(Tabla_Médico, medicoSeleccionado);
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        PanelMenu_Hospital medicos_registro = new PanelMenu_Hospital();
        medicos_registro.setSize(740, 530);
        medicos_registro.setLocation(0,0);
        contenedor.setLayout(new BorderLayout());
        contenedor.removeAll();
        contenedor.add(medicos_registro, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        icon.setIconColor(java.awt.Color.WHITE);
        BotonRegresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JComboBox<String> CB_Especialidad;
    private javax.swing.JComboBox<String> CB_Médicos;
    private javax.swing.JComboBox<String> CB_Paciente;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JTable Tabla_Médico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_especialidad;
    private javax.swing.JLabel lbl_especialidad1;
    private javax.swing.JLabel lbl_paciente;
    // End of variables declaration//GEN-END:variables
}
