/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.administrativa.hospital.la;
import java.util.Date;

import javax.swing.*;

import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;

import javax.swing.border.LineBorder;
import java.awt.*;
import javax.swing.JOptionPane;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
/**
 *
 * @author Alexis
 */
public class PanelRegistroMedicos extends javax.swing.JPanel {

    JDateChooser dateChooser = new JDateChooser();
    private JPanel contenedor;
    FontIcon icon = FontIcon.of(FontAwesomeSolid.CHEVRON_LEFT, 35);
    /**
     * Creates new form PanelRegistroPacientesd
     */
    public PanelRegistroMedicos(JPanel content) {
        initComponents();
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 210, 30));
        dateChooser.getDateEditor().setEnabled(false);
        dateChooser.getDateEditor().getUiComponent().setForeground(Color.BLACK);
        dateChooser.setBorder(new LineBorder(Color.BLUE, 2));
        
        setComponentZOrder(dateChooser, 0);
        
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setIcon(icon);
        
        contenedor = content;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        LblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBSangre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtFDNI = new javax.swing.JTextField();
        TxtFTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFCargo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtFArea = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtFEspecialidad = new javax.swing.JTextField();
        BotonRegresar = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTitulo.setFont(new java.awt.Font("Chewy", 1, 48)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(57, 74, 128));
        LblTitulo.setText("REGISTRO DE MEDICOS");
        add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 480, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRES COMPLETOS:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        TxtFNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxtFNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxtFNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA DE NACIMIENTO:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("GÉNERO:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        CBSangre.setBackground(new java.awt.Color(255, 255, 255));
        CBSangre.setForeground(new java.awt.Color(0, 0, 0));
        CBSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------------------", "A+", "A−", "B+", "B−", "AB+", "AB−", "O+", " O−" }));
        CBSangre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(CBSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 210, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        TxtFDNI.setBackground(new java.awt.Color(255, 255, 255));
        TxtFDNI.setForeground(new java.awt.Color(0, 0, 0));
        TxtFDNI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 210, 30));

        TxtFTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TxtFTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TxtFTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 210, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TELÉFONO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        TxtFCargo.setBackground(new java.awt.Color(255, 255, 255));
        TxtFCargo.setForeground(new java.awt.Color(0, 0, 0));
        TxtFCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CARGO:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        CBGenero.setBackground(new java.awt.Color(255, 255, 255));
        CBGenero.setForeground(new java.awt.Color(0, 0, 0));
        CBGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------------------", "Masculino", "Femenino" }));
        CBGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(CBGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 210, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TIPO DE SANGRE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("AREA:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        TxtFArea.setBackground(new java.awt.Color(255, 255, 255));
        TxtFArea.setForeground(new java.awt.Color(0, 0, 0));
        TxtFArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 210, 30));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 150, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ESPECIALIDAD:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        TxtFEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        TxtFEspecialidad.setForeground(new java.awt.Color(0, 0, 0));
        TxtFEspecialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 13, 236), 2));
        add(TxtFEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 210, 30));

        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/administrativa/hospital/la/registrar-medicos.jpg"))); // NOI18N
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 510));
    }//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        BaseMedicos medicos = new BaseMedicos("src/gestion/administrativa/hospital/la/medicos.json");
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = dateChooser.getDate();
        String nombre = TxtFNombre.getText().trim();
        String genero = CBGenero.getSelectedItem().toString();
        String dni = TxtFDNI.getText().trim();
        String telefono = TxtFTelefono.getText().trim();
        String especialidad = TxtFEspecialidad.getText().trim();
        String cargo = TxtFCargo.getText().trim();
        String sangre = CBSangre.getSelectedItem().toString();
        String area = TxtFArea.getText().trim();

        // Validar campos vacíos
        if (nombre.isEmpty() || fecha == null || genero.isEmpty() || dni.isEmpty() || telefono.isEmpty() ||
            especialidad.isEmpty() || cargo.isEmpty() || sangre.isEmpty() || area.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar DNI: 8 dígitos numéricos
        if (!dni.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(null, "El DNI debe tener exactamente 8 dígitos numéricos.", "DNI inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar teléfono: debe tener 9 dígitos y comenzar con 0
        if (!telefono.matches("0\\d{8}")) {
            JOptionPane.showMessageDialog(null, "El teléfono debe tener 9 dígitos y comenzar con 0.", "Teléfono inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean registro = medicos.RegistrarNuevosMedicos(TxtFNombre.getText(), 
                                            formato.format(fecha), 
                                            CBGenero.getSelectedItem().toString(), 
                                            TxtFDNI.getText(), 
                                            TxtFTelefono.getText(), 
                                            TxtFEspecialidad.getText(), 
                                            TxtFCargo.getText(), 
                                            CBSangre.getSelectedItem().toString(), 
                                            TxtFArea.getText(), 
                                            medicos.generarIDAlfanumerico());
        if (registro)
            JOptionPane.showMessageDialog(this, "Se registró un nuevo médico.", "Exito", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "No se pudo agregar al médico.", "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        Login login = new Login();
        String rol=login.rolusuario;
        if ("auditor".equalsIgnoreCase(rol)) {
    FormAuditor auditor = new FormAuditor();
    auditor.setVisible(true);
    SwingUtilities.getWindowAncestor(this).dispose();
} else if ("supervisor".equalsIgnoreCase(rol)) {
    FormSupervisor supervisor = new FormSupervisor();
    supervisor.setVisible(true);
    SwingUtilities.getWindowAncestor(this).dispose();
} else if ("medico".equalsIgnoreCase(rol)) {
    FormMedico medico = new FormMedico();
    medico.setVisible(true);
    SwingUtilities.getWindowAncestor(this).dispose();
} else {
    // Rol desconocido: vuelve a menú principal
    PanelMenu_Hospital medicos_registro = new PanelMenu_Hospital();
    medicos_registro.setSize(740, 530);
    medicos_registro.setLocation(0, 0);
    contenedor.setLayout(new BorderLayout());
    contenedor.removeAll();
    contenedor.add(medicos_registro, BorderLayout.CENTER);
    contenedor.revalidate();
    contenedor.repaint();
}
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        icon.setIconColor(java.awt.Color.WHITE);
        BotonRegresar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        icon.setIconColor(java.awt.Color.RED);
        BotonRegresar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_BotonRegresarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JComboBox<String> CBGenero;
    private javax.swing.JComboBox<String> CBSangre;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTextField TxtFArea;
    private javax.swing.JTextField TxtFCargo;
    private javax.swing.JTextField TxtFDNI;
    private javax.swing.JTextField TxtFEspecialidad;
    private javax.swing.JTextField TxtFNombre;
    private javax.swing.JTextField TxtFTelefono;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
