/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;
/**
 *
 * @author Alexis
 */
public class Registro_De_Citas extends javax.swing.JFrame {

    /**
     * Creates new form Registro_De_Citas
     */
    private BaseMedicos base_de_datos = new BaseMedicos("src/gestion/administrativa/hospital/la/medicos.json");
    private List<JSONObject> listaMedicos;
    public Registro_De_Citas() {
        initComponents();
        this.setLocationRelativeTo(null);
        base_de_datos.llenarComboEspecialidades(CB_Especialidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        Lbl_RegistroCitas = new javax.swing.JLabel();
        Lbl_RegistroCitas1 = new javax.swing.JLabel();
        lbl_especialidad = new javax.swing.JLabel();
        CB_Médicos = new javax.swing.JComboBox<>();
        CB_Especialidad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Médico = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lbl_especialidad1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(570, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_RegistroCitas.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Lbl_RegistroCitas.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_RegistroCitas.setText("Registro de Citas");
        getContentPane().add(Lbl_RegistroCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 410, -1));

        Lbl_RegistroCitas1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        Lbl_RegistroCitas1.setForeground(new java.awt.Color(57, 74, 128));
        Lbl_RegistroCitas1.setText("Registro de Citas");
        getContentPane().add(Lbl_RegistroCitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 6, 410, -1));

        lbl_especialidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_especialidad.setForeground(new java.awt.Color(0, 0, 0));
        lbl_especialidad.setText("Médico:");
        getContentPane().add(lbl_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 92, 70, -1));

        CB_Médicos.setBackground(new java.awt.Color(255, 255, 255));
        CB_Médicos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Médicos.setForeground(new java.awt.Color(0, 0, 0));
        CB_Médicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Médicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        CB_Médicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_MédicosItemStateChanged(evt);
            }
        });
        getContentPane().add(CB_Médicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 88, -1, 39));

        CB_Especialidad.setBackground(new java.awt.Color(255, 255, 255));
        CB_Especialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Especialidad.setForeground(new java.awt.Color(0, 0, 0));
        CB_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Especialidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        CB_Especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_EspecialidadItemStateChanged(evt);
            }
        });
        getContentPane().add(CB_Especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 88, -1, 39));

        Tabla_Médico.setBackground(new java.awt.Color(255, 255, 255));
        Tabla_Médico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla_Médico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos y Nombres", "ID", "Fecha", "Hora", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Médico);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 145, 654, 296));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("CONFIRMAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 5, 235), 3));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 450, 170, 50));

        lbl_especialidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_especialidad1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_especialidad1.setText("Especialidad:");
        getContentPane().add(lbl_especialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alexis\\Documents\\GitHub\\Gestor-de-Citas-HL\\src\\gestion\\administrativa\\hospital\\la\\background.jpeg")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }//GEN-END:initComponents

    public void llenarComboMedicosPorEspecialidad(JComboBox<String> combo, String especialidad) {
    combo.removeAllItems();
    for (JSONObject medico : listaMedicos) {
        if (medico.getString("especialidad").equals(especialidad)) {
            combo.addItem(medico.getString("nombre"));
        }
    }
}
    private void CB_EspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_EspecialidadItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            String especialidadSeleccionada = (String) CB_Especialidad.getSelectedItem();
            base_de_datos.llenarComboMedicos(CB_Médicos, CB_Especialidad.getSelectedItem().toString());
        }
    }//GEN-LAST:event_CB_EspecialidadItemStateChanged

    private void CB_MédicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_MédicosItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String medicoSeleccionado = (String) CB_Médicos.getSelectedItem();
        base_de_datos.llenarTablaMedicoSeleccionado(Tabla_Médico, medicoSeleccionado);
    }
    }//GEN-LAST:event_CB_MédicosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_De_Citas().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> CB_Especialidad;
    private javax.swing.JComboBox<String> CB_Médicos;
    private javax.swing.JLabel Lbl_RegistroCitas;
    private javax.swing.JLabel Lbl_RegistroCitas1;
    private javax.swing.JTable Tabla_Médico;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_especialidad;
    private javax.swing.JLabel lbl_especialidad1;
    // End of variables declaration//GEN-END:variables
}
