/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.administrativa.hospital.la;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;
/**
 *
 * @author Alexis
 */
public class Registro_De_Citas extends javax.swing.JFrame {

    /**
     * Creates new form Registro_De_Citas
     */
    private BaseMedicos base_de_datos = new BaseMedicos("src/gestion/administrativa/hospital/la/medicos.json");
    private List<JSONObject> listaMedicos;
    public Registro_De_Citas() {
        initComponents();
        this.setLocationRelativeTo(null);
        base_de_datos.llenarComboEspecialidades(CB_Especialidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        Lbl_RegistroCitas = new javax.swing.JLabel();
        lbl_especialidad = new javax.swing.JLabel();
        CB_Especialidad = new javax.swing.JComboBox<>();
        CB_Médicos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Médico = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lbl_especialidad1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(570, 820));

        Lbl_RegistroCitas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Lbl_RegistroCitas.setText("Registro de Citas");

        lbl_especialidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_especialidad.setText("Médico:");

        CB_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_EspecialidadItemStateChanged(evt);
            }
        });

        CB_Médicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Sin seleccionar---------" }));
        CB_Médicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_MédicosItemStateChanged(evt);
            }
        });

        Tabla_Médico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Apellidos y Nombres", "ID", "Fecha", "Hora", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Médico);

        jButton1.setText("Registrar CIta");

        lbl_especialidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_especialidad1.setText("Especialidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_especialidad1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lbl_especialidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB_Médicos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_RegistroCitas)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_RegistroCitas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Médicos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_especialidad)
                    .addComponent(lbl_especialidad1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    public void llenarComboMedicosPorEspecialidad(JComboBox<String> combo, String especialidad) {
    combo.removeAllItems();
    for (JSONObject medico : listaMedicos) {
        if (medico.getString("especialidad").equals(especialidad)) {
            combo.addItem(medico.getString("nombre"));
        }
    }
}
    private void CB_EspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_EspecialidadItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            String especialidadSeleccionada = (String) CB_Especialidad.getSelectedItem();
            base_de_datos.llenarComboMedicos(CB_Médicos, CB_Especialidad.getSelectedItem().toString());
        }
    }//GEN-LAST:event_CB_EspecialidadItemStateChanged

    private void CB_MédicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_MédicosItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String medicoSeleccionado = (String) CB_Médicos.getSelectedItem();
        base_de_datos.llenarTablaMedicoSeleccionado(Tabla_Médico, medicoSeleccionado);
    }
    }//GEN-LAST:event_CB_MédicosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_De_Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_De_Citas().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Especialidad;
    private javax.swing.JComboBox<String> CB_Médicos;
    private javax.swing.JLabel Lbl_RegistroCitas;
    private javax.swing.JTable Tabla_Médico;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_especialidad;
    private javax.swing.JLabel lbl_especialidad1;
    // End of variables declaration//GEN-END:variables
}
